import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";
import Image from "next/image";
import selfPortrait from "public/images/wallSelfie.jpg";
import selfPortraitMobile from "public/images/mobilePortait.jpg";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trevor Streng",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="font-mono">
      <body
        className={`${inter.className} `}
        style={
          {
            // backgroundImage: `url(${selfPortrait.src})`,
            // backgroundSize: "cover",
            // backgroundPosition: "center",
            // backgroundAttachment: "fixed",
          }
        }
      >
        {/* <Header /> */}
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
